name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.17.0'
    - name: Install packages
      run: npm i
    - name: Build a project
      run: npm run build
    - name: Setup finish
      run: echo 'Build created.'
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test dependent job"
