name: My First Github Action
on: [push]
jobs:
  build_app:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.finished.outputs.text }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.17.0'
    - name: Install packages
      run: npm i
    - name: Build a project
      run: npm run build
    - name: Deploy project to Netlify
      uses: netlify/actions/cli@master
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        SITE_ID: ${{ secrets.SITE_ID }}
      with:
        args: deploy --dir:dist --prod
        secrets: '["AUTH_TOKEN", "SITE_ID"]'
    - name: Setup finish
      id: finished
      run: echo "::set-output name=text::hello-world-from-build-job"
  test-app:
    needs: build_app
    runs-on: ubuntu-latest
    env:
      BUILD_JOB_OUTPUT: ${{needs.build_app.outputs.text }}
    steps:
      - run: echo $BUILD_JOB_OUTPUT
